sudo: required
notifications:
  email: false
language: go
go:
  - '1.9'
  - '1.10'
  - '1.11'

services:
  - docker

before_install:
  - travis_retry docker pull yandex/clickhouse-server
  - docker run -d -p 127.0.0.1:8123:8123 --name dbr-clickhouse-server yandex/clickhouse-server

install:
  - travis_retry dep ensure -v
  - go install ./vendor/...

before_script:
  - export TEST_CLICKHOUSE_DSN="http://localhost:8123/default"

script:
  - test -z "$(golint ./... | grep -v vendor | tee /dev/stderr)"
  - go vet ./...
  - test -z "$(gofmt -d -s $(find . -name \*.go -print | grep -v vendor) | tee /dev/stderr)"
  - go test -v -covermode=count -coverprofile=coverage.out .
  - goveralls -coverprofile=coverage.out -service=travis-ci
